version: '3.9'

services:
  backend_app_db:
    image: postgres:alpine
    container_name: shorty-postgres
    ports:
      - "5432:5432"
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shorty

  keycloak_db:
    image: postgres:alpine
    container_name: keycloak-postgres
    ports:
      - "5433:5432"
    networks:
      - backend
    volumes:
      - keycloak-db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_DB: postgresql
      POSTGRES_PASSWORD: postgres

  keycloak:
    container_name: shorty-keycloak
    image: quay.io/keycloak/keycloak:25.0.1
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - keycloak_db
    links:
      - keycloak_db
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_SSL_REQUIRED: none
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/postgresql
    command:
      - "start-dev"

  backend_app:
    image: shorty-image
    container_name: shorty
    depends_on:
      - backend_app_db
    ports:
      - "8000:8000"
    networks:
      - backend
    links:
      - keycloak
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://backend_app_db:5432/shorty
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      spring.oauth2.resourceserver.jwt.issuer-uri: http://keycloak:8080/realms/shorty
    entrypoint: ["java", "-jar", "shorty-api/target/shorty-api-0.0.1-SNAPSHOT.jar", "--spring.profiles.active=dev"]

  backend_test:
    image: shorty-image
    container_name: shorty-test
    depends_on:
      - backend_app_db
    networks:
      - backend
    links:
      - keycloak
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://backend_app_db:5432/shorty
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      spring.oauth2.resourceserver.jwt.issuer-uri: http://keycloak:8080/realms/shorty
    entrypoint: ["mvn", "test", "-f", "pom.xml"]

networks:
  backend:
    driver: bridge

volumes:
  keycloak-db-volume:
    external: true